language: objective-c

osx_image: xcode8

xcode_workspace: Phoenix.xcworkspace
xcode_scheme: Phoenix

xcode_sdk: macosx10.12

notifications:
  email: false

before_install:
  - npm install -g grunt-cli
  - npm install -d

script: xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build
